# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 571, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tabSuavizado = QtWidgets.QWidget()
        self.tabSuavizado.setObjectName("tabSuavizado")
        self.groupBox = QtWidgets.QGroupBox(self.tabSuavizado)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 481, 291))
        self.groupBox.setObjectName("groupBox")
        self.label_0 = QtWidgets.QLabel(self.groupBox)
        self.label_0.setGeometry(QtCore.QRect(10, 40, 231, 21))
        self.label_0.setObjectName("label_0")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 80, 66, 17))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 66, 17))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 151, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 141, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_exp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_exp.setGeometry(QtCore.QRect(350, 80, 113, 21))
        self.lineEdit_exp.setObjectName("lineEdit_exp")
        self.lineEdit_dias = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_dias.setGeometry(QtCore.QRect(350, 110, 113, 21))
        self.lineEdit_dias.setObjectName("lineEdit_dias")
        self.lineEdit_incrementoM4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_incrementoM4.setGeometry(QtCore.QRect(350, 140, 113, 21))
        self.lineEdit_incrementoM4.setObjectName("lineEdit_incrementoM4")
        self.lineEdit_incrementoM6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_incrementoM6.setGeometry(QtCore.QRect(350, 170, 113, 21))
        self.lineEdit_incrementoM6.setObjectName("lineEdit_incrementoM6")
        self.lineEdit_velOperM4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_velOperM4.setGeometry(QtCore.QRect(350, 200, 113, 21))
        self.lineEdit_velOperM4.setObjectName("lineEdit_velOperM4")
        self.lineEdit_velOperM6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_velOperM6.setGeometry(QtCore.QRect(350, 230, 113, 21))
        self.lineEdit_velOperM6.setObjectName("lineEdit_velOperM6")
        self.line_1 = QtWidgets.QFrame(self.groupBox)
        self.line_1.setGeometry(QtCore.QRect(0, 20, 481, 20))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(0, 60, 481, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 260, 201, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit_diasProd = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_diasProd.setGeometry(QtCore.QRect(350, 260, 113, 21))
        self.lineEdit_diasProd.setObjectName("lineEdit_diasProd")
        self.line_3 = QtWidgets.QFrame(self.tabSuavizado)
        self.line_3.setGeometry(QtCore.QRect(30, 300, 471, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_6 = QtWidgets.QLabel(self.tabSuavizado)
        self.label_6.setGeometry(QtCore.QRect(30, 240, 131, 17))
        self.label_6.setObjectName("label_6")
        self.btnSimulacion = QtWidgets.QPushButton(self.tabSuavizado)
        self.btnSimulacion.setGeometry(QtCore.QRect(220, 330, 89, 25))
        self.btnSimulacion.setObjectName("btnSimulacion")
        self.tabWidget.addTab(self.tabSuavizado, "")
        self.tabResultados = QtWidgets.QWidget()
        self.tabResultados.setObjectName("tabResultados")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabResultados)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 231, 281))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.primerGrafico = QtWidgets.QLabel(self.groupBox_3)
        self.primerGrafico.setGeometry(QtCore.QRect(0, 30, 211, 261))
        self.primerGrafico.setText("")
        self.primerGrafico.setScaledContents(True)
        self.primerGrafico.setObjectName("primerGrafico")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabResultados)
        self.groupBox_4.setGeometry(QtCore.QRect(270, 20, 241, 281))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.segundoGrafico = QtWidgets.QLabel(self.groupBox_4)
        self.segundoGrafico.setGeometry(QtCore.QRect(0, 30, 211, 261))
        self.segundoGrafico.setText("")
        self.segundoGrafico.setScaledContents(True)
        self.segundoGrafico.setObjectName("segundoGrafico")
        self.label_8 = QtWidgets.QLabel(self.tabResultados)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 201, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_resultado = QtWidgets.QLineEdit(self.tabResultados)
        self.lineEdit_resultado.setGeometry(QtCore.QRect(270, 320, 231, 21))
        self.lineEdit_resultado.setObjectName("lineEdit_resultado")
        self.tabWidget.addTab(self.tabResultados, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tp Final Modelos y Simulación"))
        self.groupBox.setTitle(_translate("MainWindow", "Parámetros"))
        self.label_0.setText(_translate("MainWindow", "Ingrese los datos para simular:"))
        self.label_1.setText(_translate("MainWindow", "Meses:"))
        self.label_2.setText(_translate("MainWindow", "Días x mes:"))
        self.label_5.setText(_translate("MainWindow", "velOperM4:"))
        self.label_3.setText(_translate("MainWindow", "incrementoStockM4:"))
        self.label_4.setText(_translate("MainWindow", "incrementoStockM6:"))
        self.label_7.setText(_translate("MainWindow", "Cantidad días producción:"))
        self.label_6.setText(_translate("MainWindow", "velOperM6:"))
        self.btnSimulacion.setText(_translate("MainWindow", "Simular"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSuavizado), _translate("MainWindow", "Simulación"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gráfico 1ra. Corrida"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Gráfico 2da. Corrida"))
        self.label_8.setText(_translate("MainWindow", "Resultado de la simulación:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabResultados), _translate("MainWindow", "Resultados"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

